version: "3.8"

networks:
  default:
    external:
      name: my-bridge-network

services:
  postgres:
    image: postgres:alpine3.17
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


















